name:                subworld
version:             0.1.0.0
github:              "andymac-2/subworld"
license:             BSD3
author:              "Andrew Pritchard"
maintainer:          "https://github.com/andymac-2"
copyright:           "2018 Andrew Pritchard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/andymac-2/new-template#readme>

dependencies:
- base >= 4.7 && < 5
- text
- parsec
- unordered-containers

library:
  source-dirs: src

executables:
  sc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subworld

tests:
  sc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subworld
